### ISSUE TITLE
Karma tests are failing

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/teem#159]
The message it gives is: karma is not a function. It may be caused by a recent update of karma.

**Comment by atd** [comment]
Please, could you double check the version in `node_modules/karma`

Also, could you paste the error trace?

**Comment by llopv** [comment]
Yes, I needed a `npm install`.

Now what is failing is protractor when I do `gulp test`. The README is outdated since `npm run test-single-run`, `npm run update-webdriver`, and `npm run protractor` don't work.

I copy here the trace:

```
...
[12:05:18] gulp-angular-protractor - Webdriver standalone will be updated
selenium standalone is up to date.
chromedriver is up to date.
[12:05:18] gulp-angular-protractor - Webdriver standalone is updated
[12:05:18] gulp-angular-protractor - Webdriver standalone server will be started
04 02 2016 12:05:18.739:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket /#16CmpQHxiIb9wOx4AAAA with id 8865698
PhantomJS 1.9.8 (Linux 0.0.0): Executed 0 of 3 SUCCESS (0 secs / 0 secs)
[12:05:18] seleniumProcess.pid: undefined

[12:05:18] events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3

[12:05:18] gulp-angular-protractor - Webdriver standalone server will be closed
PhantomJS 1.9.8 (Linux 0.0.0): Executed 3 of 3 SUCCESS (0.031 secs / 0.052 secs)
[12:05:19] Finished 'test:unit' after 839 ms
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

/home/bernadet/teem2/gulpfile.js:482
    .on('error', function(e) { connect.serverClose(); throw e; })
                                                      ^
Error: protractor exited with code 1
```

**Comment by atd** [comment]
It looks like you need a Java JDK

https://github.com/angular/protractor/issues/369

Another install issue found!

**Comment by llopv** [comment]
Yes, now tests are working for me. I updated the README (https://github.com/P2Pvalue/teem/commit/f69cd21b053bca62d562bf3b4dab6ebd87bf382c).
